/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:45b307e8-f2b7-430c-878f-0a0610607ed9",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_a4l8ON2mh",
    "aws_user_pools_web_client_id": "5po3aeppnhfb0catu0pe9hp3os",
    "oauth": {},
    "aws_user_files_s3_bucket": "awsamplifygraphql61bbd92df4824110bca6a6290aa6d0133533-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://7gmgwd7zpnadrbx34mz2j3i5by.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
